// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs8GLS5--9coOEpIznzSOZ1rprwYNyjf0',
    appId: '1:969166695288:web:436b0da7c3e4bc1b35368d',
    messagingSenderId: '969166695288',
    projectId: 'flutter-clone-2023',
    authDomain: 'flutter-clone-2023.firebaseapp.com',
    storageBucket: 'flutter-clone-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJs2_cWlQqRDZ7fkltR3grjcIv53As70o',
    appId: '1:969166695288:android:6d76af909e90724535368d',
    messagingSenderId: '969166695288',
    projectId: 'flutter-clone-2023',
    storageBucket: 'flutter-clone-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7gf_4sfH74BiRNmaAESr_Wh9Z6d0zemo',
    appId: '1:969166695288:ios:c3db4b09a904577e35368d',
    messagingSenderId: '969166695288',
    projectId: 'flutter-clone-2023',
    storageBucket: 'flutter-clone-2023.appspot.com',
    iosClientId: '969166695288-1dn96thl3d1dqfi7put4ifktq6026vp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7gf_4sfH74BiRNmaAESr_Wh9Z6d0zemo',
    appId: '1:969166695288:ios:c3db4b09a904577e35368d',
    messagingSenderId: '969166695288',
    projectId: 'flutter-clone-2023',
    storageBucket: 'flutter-clone-2023.appspot.com',
    iosClientId: '969166695288-1dn96thl3d1dqfi7put4ifktq6026vp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chill',
  );
}
